---
- name: Backup Wazuh Server Configuration
  hosts: all
  become: yes
  tasks:
   
    - name: Define the backup directory
      set_fact:
        backup_dir: "/var/ossec/backup/wazuh_config"

    - name: Ensure the backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Create timestamp for backup
      set_fact:
        timestamp: "{{ ansible_date_time }}"

    - name: Backup Wazuh configuration files
      command: "tar -czf {{ backup_dir }}/wazuh_config_{{ timestamp }}.tar.gz /var/ossec/etc"
      register: backup_result
      failed_when: backup_result.rc != 0

    - name: Verify backup was successful
      debug:
        msg: "Wazuh configuration backed up successfully at {{ backup_dir }}/wazuh_config_{{ timestamp }}.tar.gz"
      when: backup_result.rc == 0
      
    - name: Log failure if backup failed
      debug:
        msg: "Backup failed with error: {{ backup_result.stderr }}"
      when: backup_result.rc != 0
