- name: Generate Compliance Report
  hosts: wazuh_server
  become: yes
  vars:
    compliance_standards: ["PCI DSS", "GDPR", "NIST 800-53"]
    report_path: "/var/reports/wazuh_compliance_report_{{ ansible_date_time.year }}_{{ ansible_date_time.month }}.log"

  tasks:
    - name: Create report directory if not exists
      file:
        path: /var/reports
        state: directory

    - name: Fetch compliance data for each standard
      uri:
        url: "http://{{ ansible_host }}:55000/compliance/{{ item }}"
        method: GET
        headers:
          Authorization: "Bearer YOUR_WAZUH_API_TOKEN"
        return_content: yes
      register: compliance_results
      with_items: "{{ compliance_standards }}"

    - name: Write compliance results to report
      lineinfile:
        path: "{{ report_path }}"
        line: "Standard: {{ item.item }}, Status: {{ item.json.status }}"
      with_items: "{{ compliance_results.results }}"

    - name: Display report location
      debug:
        msg: "Compliance report generated at {{ report_path }}"
