---
- name: Check Wazuh Manager Version
  hosts: all
  become: yes
  tasks:
    - name: Check if Wazuh Manager is installed
      shell: /var/ossec/bin/wazuh-control info
      register: wazuh_version
      ignore_errors: yes

    - name: Display Wazuh Manager version
      debug:
        msg: >
          {% if wazuh_version.stdout %}
          Wazuh Manager is installed. Current version:
          {{ wazuh_version.stdout }}
          {% else %}
          Wazuh Manager is not installed or command not found.
          {% endif %}
