---
- name: Wazuh Log Monitoring
  hosts: all
  become: yes
  tasks:
    - name: Show recent Wazuh log entries
      command: tail -n 50 /var/ossec/logs/ossec.log
      register: wazuh_log_output

    - name: Display Wazuh log output
      debug:
        msg: "{{ wazuh_log_output.stdout }}"
