---
- name: Check Wazuh Version
  hosts: all
  become: yes
  tasks:
    - name: Get Wazuh Manager version
      command: wazuh-manager -v
      register: wazuh_manager_version
      changed_when: false

    - name: Get Wazuh Agent version
      command: wazuh-agent -v
      register: wazuh_agent_version
      changed_when: false

    - name: Show Wazuh Manager version
      debug:
        msg: "Wazuh Manager version: {{ wazuh_manager_version.stdout }}"

    - name: Show Wazuh Agent version
      debug:
        msg: "Wazuh Agent version: {{ wazuh_agent_version.stdout }}"
