---
- name: Wazuh Log Monitoring
  hosts: all
  become: yes
  tasks:
    - name: Show the last 50 Wazuh log entries
      command: tail -n 50 /var/ossec/logs/ossec.log
      register: wazuh_log_output

    - name: Display each line of Wazuh log output
      debug:
        msg: "{{ item }}"
      loop: "{{ wazuh_log_output.stdout_lines }}"
