---
- name: Delete August
  hosts: all
  become: yes
  tasks:
    - name: Delete August
      file:
        path: "/var/ossec/logs/alerts/Aug/"
        state: absent
      register: deleted_file

    - name: Show success message if file was deleted
      debug:
        msg: "Success"
      when: deleted_file is not failed

    - name: Show failure message if file was not deleted
      debug:
        msg: "Failed"
      when: deleted_file is failed
