---
- name: Check Wazuh Manager Service Status
  hosts: all
  become: yes
  tasks:
    
    - name: Check the status of Wazuh Manager service
      systemd:
        name: wazuh-manager
        state: started
      register: wazuh_status
      failed_when: false  

    - name: Display Wazuh on message
      debug:
        msg: "Wazuh on"
      when: wazuh_status.status.ActiveState == 'active' and wazuh_status.status.SubState == 'running'
