---
- name: Check Wazuh Manager Service Status
  hosts: all
  become: yes
  tasks:
    # Kiểm tra trạng thái của dịch vụ Wazuh Manager
    - name: Check the status of Wazuh Manager service
      systemd:
        name: wazuh-manager
        state: started
      register: wazuh_status
      failed_when: false  # Không làm thất bại nếu dịch vụ không chạy

    # Hiển thị thông báo "Wazuh on" nếu dịch vụ đang chạy
    - name: Display Wazuh on message
      debug:
        msg: "Wazuh on"
      when: wazuh_status.status.ActiveState == 'active' and wazuh_status.status.SubState == 'running'

    # Hiển thị thông báo "Wazuh off" nếu dịch vụ không chạy
    - name: Display Wazuh off message
      debug:
        msg: "Wazuh off"
      when: wazuh_status.status.ActiveState != 'active' or wazuh_status.status.SubState != 'running'
