---
- name: Extract Malware Detection Logs with Level >= 7
  hosts: 192.168.10.187
  become: yes
  tasks:
    # 1. Kiểm tra file alerts.json tồn tại
    - name: Check if alerts log exists
      stat:
        path: /var/ossec/logs/alerts/alerts.json
      register: alerts_log

    - name: Abort if alerts log does not exist
      fail:
        msg: "The Wazuh alerts log file does not exist at /var/ossec/logs/alerts/alerts.json"
      when: not alerts_log.stat.exists

    # 2. Lọc các cảnh báo liên quan đến Malware Detection (rule.level >= 7)
    - name: Filter malware detection logs with level >= 7
      shell: >
        jq '.[] | select(.rule.level >= 7 and (.rule.groups[] | contains("malware-detection")))' /var/ossec/logs/alerts/alerts.json
      register: filtered_malware_logs

    # 3. Lưu log đã lọc vào một file báo cáo
    - name: Save filtered malware logs to a file
      copy:
        content: "{{ filtered_malware_logs.stdout }}"
        dest: /var/ossec/logs/alerts/malware_detection_lv7.json
        mode: '0644'

    # 4. Hiển thị thông báo nếu log đã lưu
    - name: Display saved malware logs
      debug:
        msg: >
          Malware detection logs saved to /var/ossec/logs/alerts/malware_detection_lv7.json.
          Details:
          {{ filtered_malware_logs.stdout if filtered_malware_logs.stdout else "No malware detection logs with level >= 7 found." }}

    # 5. (Tùy chọn) Tải báo cáo về máy điều khiển
    - name: Fetch malware detection report to control machine
      fetch:
        src: /var/ossec/logs/alerts/malware_detection_lv7.json
        dest: ./reports/malware_detection_lv7_{{ inventory_hostname }}.json
        flat: yes
