---
- name: Malware Detection
  hosts: all
  become: yes
  tasks:
    # 1. Cài đặt ClamAV
    - name: Install ClamAV on Debian/Ubuntu
      apt:
        name: clamav
        state: latest
      when: ansible_os_family == "Debian"

    - name: Install ClamAV on RedHat/CentOS
      yum:
        name: clamav
        state: latest
      when: ansible_os_family == "RedHat"

    # 2. Cập nhật cơ sở dữ liệu virus
    - name: Update ClamAV database
      command: freshclam
      register: freshclam_output

    - name: Display ClamAV database update output
      debug:
        msg: "{{ freshclam_output.stdout }}"

    # 3. Quét thư mục cụ thể
    - name: Run malware scan on /var directory
      command: clamscan -r /var
      register: scan_result

    - name: Display malware scan results
      debug:
        msg: >
          Malware scan results:
          {{ scan_result.stdout_lines | join("\n") if scan_result.stdout_lines else "No issues found during the scan." }}

    # 4. Gửi thông báo nếu phát hiện file bị nhiễm
    - name: Check for infected files
      debug:
        msg: "Infected files found! Details: {{ scan_result.stdout_lines | join('\n') }}"
      when: "'Infected files' in scan_result.stdout"
