---
- name: Restore Wazuh Server Configuration
  hosts: all
  become: yes
  vars:
    backup_dir: "/var/backups/wazuh_config"
    restore_timestamp: "20241210T212517761260"
    backup_file: "{{ backup_dir }}/wazuh_config_{{ restore_timestamp }}.tar.gz"
  tasks:
    # Kiểm tra file backup tồn tại
    - name: Check if the backup file exists
      stat:
        path: "{{ backup_file }}"
      register: backup_file_check

    # Dừng nếu file backup không tồn tại
    - name: Abort if backup file does not exist
      fail:
        msg: "The specified backup file does not exist: {{ backup_file }}. Cannot proceed with restore!"
      when: not backup_file_check.stat.exists

    # Đảm bảo thư mục /var/ossec tồn tại và có quyền ghi
    - name: Ensure /var/ossec exists and is writable
      file:
        path: "/var/ossec"
        state: directory
        mode: '0755'

    # Giải nén file backup để khôi phục
    - name: Extract the backup file to restore configuration
      shell: "tar -xzf {{ backup_file }} -C /var/ossec"
      register: restore_result
      failed_when: restore_result.rc != 0

    # Xác nhận khôi phục thành công
    - name: Verify restore was successful
      debug:
        msg: "Wazuh configuration restored successfully from {{ backup_file }}"
      when: restore_result.rc == 0

    # Ghi log nếu khôi phục thất bại
    - name: Log failure if restore failed
      debug:
        msg: "Restore failed with error: {{ restore_result.stderr }}"
      when: restore_result.rc != 0
