---
- name: Manage Wazuh Service
  hosts: all
  become: yes
  tasks:
    - name: Restart Wazuh Manager service
      systemd:
        name: wazuh-manager
        state: restarted
      register: restart_result
      
    - name: Display restart result
      debug:
        msg: "Wazuh Manager service has been restarted successfully"
      when: restart_result.changed

    - name: Verify Wazuh Manager service status after restart
      systemd:
        name: wazuh-manager
        state: started
      register: after_restart_status

    - name: Display Wazuh service status after restart
      debug:
        msg: "Wazuh Manager service status after restart: {{ after_restart_status.state }}"
      when: after_restart_status.state is defined
