---
- name: Restore Wazuh Server Configuration
  hosts: all
  become: yes
  tasks:
    
    - name: Define the backup directory and file
      set_fact:
        backup_dir: "/var/ossec/backup/wazuh_config"
        backup_file: "{{ backup_dir }}/wazuh_config_{{ restore_timestamp }}.tar.gz"  # Replace with the backup timestamp if needed

    - name: Ensure Wazuh configuration directory exists
      file:
        path: "/var/ossec/etc"
        state: directory
        mode: '0755'

    - name: Check if the backup file exists
      stat:
        path: "{{ backup_file }}"
      register: backup_stat

    - name: Fail if the backup file does not exist
      fail:
        msg: "Backup file {{ backup_file }} does not exist!"
      when: backup_stat.stat.exists == False

    - name: Restore Wazuh configuration files from backup
      command: "tar -xzf {{ backup_file }} -C /var/ossec"
      register: restore_result
      failed_when: restore_result.rc != 0

    - name: Verify restore was successful
      debug:
        msg: "Wazuh configuration restored successfully from {{ backup_file }}"
      when: restore_result.rc == 0
      
    - name: Log failure if restore failed
      debug:
        msg: "Restore failed with error: {{ restore_result.stderr }}"
      when: restore_result.rc != 0

    - name: Restart Wazuh Manager service to apply restored configuration
      systemd:
        name: wazuh-manager
        state: restarted
