---
- name: Show full Wazuh log for December 17, 2024
  hosts: all
  become: true
  gather_facts: no
  vars:
    log_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"

  tasks:
    - name: Read full log file content
      slurp:
        src: "{{ log_file }}"
      register: full_log

    - name: Decode and display full log content
      debug:
        msg: "{{ full_log['content'] | b64decode }}"
