---
- name: Show full Wazuh log for December 17, 2024 with level > 4
  hosts: all
  become: true
  gather_facts: no
  vars:
    log_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"

  tasks:
    - name: Read full log file content
      slurp:
        src: "{{ log_file }}"
      register: full_log

    - name: Decode log content
      set_fact:
        decoded_logs: "{{ full_log['content'] | b64decode | splitlines }}"

    - name: Parse and filter logs with level > 4
      set_fact:
        filtered_logs: >-
          {{ decoded_logs | map('from_json') | selectattr('level', 'gt', 4) | list }}

    - name: Display filtered log content
      debug:
        msg: "{{ filtered_logs }}"
