---
- name: Show machine names from Wazuh log
  hosts: all
  become: true
  gather_facts: no
  vars:
    log_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"

  tasks:
    - name: Read full log file content
      slurp:
        src: "{{ log_file }}"
      register: full_log

    - name: Decode and split log lines
      set_fact:
        log_lines: "{{ full_log['content'] | b64decode | split('\n') }}"

    - name: Parse JSON logs and extract machine name
      set_fact:
        machine_names: "{{ log_lines |
                           map('regex_replace', '^(.*)$', '\\1') |           # Ensure lines are treated as strings
                           map('from_json', default={}) |                   # Parse to JSON (ignore errors)
                           selectattr('agent.name', 'defined') |            # Check if 'agent.name' exists
                           map(attribute='agent.name') | unique | list }}"  # Extract 'agent.name', remove duplicates

    - name: Display machine names
      debug:
        msg: "Machine Name: {{ item }}"
      loop: "{{ machine_names }}"
