---
- name: Extract Wazuh log alerts with level >= 5
  hosts: all
  become: true
  gather_facts: no
  vars:
    log_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"

  tasks:
    - name: Read full log file content
      slurp:
        src: "{{ log_file }}"
      register: full_log

    - name: Split, validate and filter logs by level >= 5
      set_fact:
        filtered_logs: >-
          {{ full_log['content'] | b64decode | split('\n')
             | select('search', '^{.*}$')   # Chỉ chọn các dòng JSON hợp lệ
             | map('extract_json_safe')     # Parse từng dòng JSON an toàn
             | selectattr('rule.level', '>=', 5)  # Lọc theo level >= 5
             | list }}

    - name: Display valid logs with id, level, and description
      debug:
        msg: "ID: {{ item.rule.id }}, Level: {{ item.rule.level }}, Description: {{ item.rule.description }}"
      loop: "{{ filtered_logs }}"

# Custom filter to safely parse JSON
- name: Add custom filter for safe JSON parsing
  filters:
    extract_json_safe: |
      def extract_json_safe(line):
          try:
              return json.loads(line)
          except:
              return None
