---
- name: Xử lý cảnh báo Wazuh mức độ cao qua SSH
  hosts: 192.168.10.187
  become: yes
  vars:
    alert_level_threshold: 10
    wazuh_alerts_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"

  tasks:
    - name: Cài đặt jq nếu chưa có
      package:
        name: jq
        state: present

    - name: Đọc file cảnh báo Wazuh và lọc theo level >= {{ alert_level_threshold }}
      shell: "tail -n 1000 {{ wazuh_alerts_file }} | jq -c 'select(.rule.level >= {{ alert_level_threshold }})'"
      register: high_level_alerts
      changed_when: false  # Không đánh dấu task này là 'changed'

    - name: Kiểm tra có cảnh báo nào không
      fail:
        msg: "Không có cảnh báo nào có level >= {{ alert_level_threshold }}"
      when: high_level_alerts.stdout == ""

    - name: Hiển thị cảnh báo mức độ cao
      debug:
        msg: "Cảnh báo mức độ cao: {{ item.rule.description }} - Level: {{ item.rule.level }}"
      loop: "{{ high_level_alerts.stdout_lines | map('from_json') | list }}"
