---
- name: Filter Wazuh logs for alerts with level >= 5
  hosts: 192.168.10.187
  become: yes
  gather_facts: no
  vars:
    log_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"
    output_file: "./ThreatHungting_alerts_level_5.json"

  tasks:
    - name: Read log file content
      slurp:
        src: "{{ log_file }}"
      register: raw_log

    - name: Decode and filter alerts with rule.level >= 5
      set_fact:
        filtered_alerts: "{{ raw_log['content'] | b64decode | splitlines | map('from_json') | selectattr('rule.level', '>=', 5) | list }}"

    - name: Save filtered alerts to a file
      copy:
        content: "{{ filtered_alerts | to_nice_json }}"
        dest: "{{ output_file }}"
      when: filtered_alerts | length > 0

    - name: Display filtered alerts
      debug:
        msg: "{{ filtered_alerts }}"
