- name: Threat Hunting - Suspicious Logins
  hosts: all
  become: yes
  tasks:
    - name: Search for failed logins
      command: "grep 'Failed password' /var/ossec/logs/alerts/alerts.log"
      register: failed_logins

    - name: Display failed login attempts
      debug:
        msg: "{{ failed_logins.stdout }}"
