---
- name: Show full Wazuh log for December 17, 2024 with level > 4
  hosts: all
  become: true
  gather_facts: no
  vars:
    log_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"

  tasks:
    - name: Read full log file content
      slurp:
        src: "{{ log_file }}"
      register: full_log

    - name: Decode log content and split lines
      set_fact:
        decoded_logs: "{{ full_log['content'] | b64decode | split('\n') }}"

    - name: Parse and filter logs with level > 4
      set_fact:
        filtered_logs: >-
          {{ decoded_logs 
             | select('search', '{')  # Chọn các dòng JSON hợp lệ
             | map('from_json')       # Parse JSON
             | selectattr('level', 'gt', 4) 
             | list 
          }}

    - name: Display filtered log content
      debug:
        msg: "{{ filtered_logs }}"
