---
- name: Show Wazuh log with rule.level > 4
  hosts: all
  become: true
  gather_facts: no
  vars:
    log_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"

  tasks:
    - name: Read full log file content
      slurp:
        src: "{{ log_file }}"
      register: full_log

    - name: Decode and split log lines
      set_fact:
        log_lines: "{{ full_log['content'] | b64decode | split('\n') }}"

    - name: Parse JSON logs and filter rule.level > 4
      set_fact:
        filtered_logs: "{{ log_lines | map('from_json', default={}) | selectattr('rule.level', 'defined') | selectattr('rule.level', '>', 4) | list }}"

    - name: Display filtered logs
      debug:
        msg: "Timestamp: {{ item.timestamp }}, Level: {{ item.rule.level }}, Description: {{ item.rule.description }}"
      loop: "{{ filtered_logs }}"
