---
- name: Show full Wazuh log with each log on a new line
  hosts: all
  become: true
  gather_facts: no
  vars:
    log_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"

  tasks:
    - name: Read full log file content
      slurp:
        src: "{{ log_file }}"
      register: full_log

    - name: Decode and split logs into lines
      set_fact:
        log_lines: "{{ full_log['content'] | b64decode | from_json | list }}"

    - name: Display each log on a new line
      debug:
        msg: "{{ item }}"
      loop: "{{ log_lines }}"
