---
- name: Extract Wazuh alerts with level >= 5
  hosts: all
  become: true
  gather_facts: no
  vars:
    log_file: "/var/ossec/logs/alerts/2024/Dec/ossec-alerts-17.json"

  tasks:
    - name: Read full log file content
      slurp:
        src: "{{ log_file }}"
      register: raw_log

    - name: Decode and split log lines
      set_fact:
        log_lines: "{{ raw_log['content'] | b64decode | split('\n') }}"

    - name: Parse and filter valid logs with level >= 5
      set_fact:
        filtered_logs: "{{ log_lines | map('from_json', default={}) | selectattr('rule.level', 'defined') | selectattr('rule.level', '>=', 5) | list }}"

    - name: Display logs with ID, Level, and Description
      debug:
        msg: "ID: {{ item.rule.id }}, Level: {{ item.rule.level }}, Description: {{ item.rule.description }}"
      loop: "{{ filtered_logs }}"
