---
- name: High Level Alert
  hosts: 192.168.10.187
  become: yes
  vars:
    alert_level_threshold: 9
    wazuh_alerts_file: "/var/ossec/logs/alerts/2025/Jan/ossec-alerts-16.json"

  tasks:
    - name: Install jq if not have
      package:
        name: jq
        state: present

    - name: Search Alert
      shell: |
        tail -n 1000 {{ wazuh_alerts_file }} | \
        grep '^{.*}$' | jq -c 'select(.rule.level != null and .rule.level >= {{ alert_level_threshold }})'
      register: high_level_alerts
      changed_when: false

    - name: Check if not high aleft
      fail:
        msg: "NO >= {{ alert_level_threshold }}"
      when: high_level_alerts.stdout == ""

    - name: Show High Level
      debug:
        msg: "High Level: {{ item.rule.description }} - Level: {{ item.rule.level }}"
      loop: "{{ high_level_alerts.stdout_lines | map('from_json') | list }}"
