- name: Generate monthly compliance report from Wazuh
  hosts: localhost
  gather_facts: no
  vars:
    wazuh_api_url: "http://<wazuh_server_ip>:55000"
    wazuh_api_token: "your_api_token_here"
    compliance_report_dir: "/var/reports/wazuh_compliance"
    compliance_report_file: "wazuh_compliance_report_{{ ansible_date_time.year }}_{{ ansible_date_time.month }}.log"

  tasks:
    - name: Ensure compliance report directory exists
      file:
        path: "{{ compliance_report_dir }}"
        state: directory
        mode: '0755'

    - name: Fetch compliance data from Wazuh
      uri:
        url: "{{ wazuh_api_url }}/sca"
        method: GET
        headers:
          Authorization: "Bearer {{ wazuh_api_token }}"
        return_content: yes
        status_code: 200
      register: compliance_data

    - name: Parse compliance data
      set_fact:
        compliance_results: "{{ compliance_data.json.data }}"

    - name: Generate compliance report header
      copy:
        content: |
          Wazuh Monthly Compliance Report - {{ ansible_date_time.year }}/{{ ansible_date_time.month }}
          ===========================================================
          \n
        dest: "{{ compliance_report_dir }}/{{ compliance_report_file }}"
        force: yes

    - name: Append compliance results to report
      lineinfile:
        path: "{{ compliance_report_dir }}/{{ compliance_report_file }}"
        line: "Agent: {{ item.agent.name }}, CIS Profile: {{ item.policy }}, Passed: {{ item.passed }}, Failed: {{ item.failed }}"
      with_items: "{{ compliance_results }}"
      when: item.agent.name is defined

    - name: Notify if compliance failed
      debug:
        msg: "One or more agents have compliance issues. Check the report at {{ compliance_report_dir }}/{{ compliance_report_file }}"
      when: "'Failed' in item.failed | string"
      with_items: "{{ compliance_results }}"

    - name: Display report location
      debug:
        msg: "Monthly compliance report saved at {{ compliance_report_dir }}/{{ compliance_report_file }}"
