---
- name: Update Wazuh Server
  hosts: all
  become: yes
  vars:
    wazuh_repo_url: "https://packages.wazuh.com/4.x/"
    wazuh_gpg_key: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"

  tasks:
    # Đảm bảo kho Wazuh được cấu hình
    - name: Add Wazuh repository (Debian/Ubuntu)
      apt_repository:
        repo: "deb {{ wazuh_repo_url }}apt stable main"
        state: present
        filename: wazuh
      when: ansible_os_family == "Debian"

    - name: Add Wazuh repository (CentOS/RHEL)
      yum_repository:
        name: wazuh
        description: Wazuh repository
        baseurl: "{{ wazuh_repo_url }}yum/"
        gpgcheck: yes
        gpgkey: "{{ wazuh_gpg_key }}"
      when: ansible_os_family == "RedHat"

    # Cập nhật danh sách gói
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    # Cập nhật Wazuh Server
    - name: Update Wazuh Server package
      package:
        name: wazuh-manager
        state: latest

    # Kiểm tra phiên bản Wazuh Server sau khi cập nhật
    - name: Check Wazuh Server version
      command: "/var/ossec/bin/wazuh-control -v"
      register: wazuh_server_version

    - name: Display Wazuh Server version
      debug:
        msg: "Wazuh Server updated to version: {{ wazuh_server_version.stdout }}"
