---
- name: Update Wazuh Server
  hosts: 192.168.10.187
  become: yes
  vars:
    wazuh_packages:
      - wazuh-manager

  tasks:
    # Cập nhật gói Wazuh
    - name: Update Wazuh packages
      package:
        name: "{{ wazuh_packages }}"
        state: latest

    # Kiểm tra phiên bản sau khi cập nhật
    - name: Check Wazuh Manager version
      command: /var/ossec/bin/wazuh-manager -v
      register: wazuh_version

    - debug:
        msg: "Updated Wazuh Manager Version: {{ wazuh_version.stdout }}"
