---
- name: Update Wazuh Server
  hosts: wazuh-manager
  become: yes
  tasks:

    # Step 1: Check OS family and update the repository
    - name: Add Wazuh repository for Debian/Ubuntu
      apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Wazuh repository for RedHat/CentOS
      yum_repository:
        name: wazuh
        description: "Wazuh repository"
        baseurl: https://packages.wazuh.com/4.x/rpm/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present
      when: ansible_os_family == "RedHat"

    # Step 2: Update the package cache
    - name: Update package cache for Debian/Ubuntu
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package cache for RedHat/CentOS
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    # Step 3: Upgrade Wazuh Manager to the latest version
    - name: Upgrade Wazuh Manager on Debian/Ubuntu
      apt:
        name: wazuh-manager
        state: latest
      when: ansible_os_family == "Debian"

    - name: Upgrade Wazuh Manager on RedHat/CentOS
      yum:
        name: wazuh-manager
        state: latest
      when: ansible_os_family == "RedHat"

    # Step 4: Check Wazuh Manager version after the upgrade
    - name: Get the current Wazuh Manager version
      command: wazuh-manager -v
      register: wazuh_version
      changed_when: false

    - name: Display the current Wazuh Manager version
      debug:
        msg: "Wazuh Manager version: {{ wazuh_version.stdout }}"

    # Step 5: Restart Wazuh Manager service
    - name: Restart Wazuh Manager service
      systemd:
        name: wazuh-manager
        state: restarted

    # Step 6: Ensure Wazuh Manager service is running
    - name: Ensure Wazuh Manager service is running and enabled
      systemd:
        name: wazuh-manager
        state: started
        enabled: yes
