---
- name: Update and Backup Wazuh
  hosts: 192.168.10.187
  become: true
 
  gather_facts: no
  tasks:
    - name: Ensure Wazuh is updated to the latest version
      apt:
        name: wazuh-manager
        state: latest
      register: update_result

    - name: Notify if Wazuh was updated
      debug:
        msg: "Wazuh has been updated to the latest version."
      when: update_result.changed
