---
- name: Update Wazuh Server
  hosts: all
  become: yes
  tasks:
    # Step 1: Cập nhật danh sách gói
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package cache (RedHat-based systems)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    # Step 2: Nâng cấp gói Wazuh Manager lên phiên bản mới nhất
    - name: Upgrade Wazuh Manager to the latest version (Debian/Ubuntu)
      apt:
        name: wazuh-manager
        state: latest
      when: ansible_os_family == "Debian"

    - name: Upgrade Wazuh Manager to the latest version (RedHat/CentOS)
      yum:
        name: wazuh-manager
        state: latest
      when: ansible_os_family == "RedHat"

    # Step 3: Kiểm tra phiên bản Wazuh sau khi cập nhật
    - name: Get Wazuh Manager version
      command: wazuh-manager -v
      register: wazuh_version
      changed_when: false

    - name: Display the Wazuh Manager version
      debug:
        msg: "Wazuh Manager is now running version {{ wazuh_version.stdout }}"

    # Step 4: Khởi động lại dịch vụ Wazuh Manager
    - name: Restart Wazuh Manager service
      systemd:
        name: wazuh-manager
        state: restarted

    # Step 5: Đảm bảo dịch vụ Wazuh Manager đang chạy
    - name: Ensure Wazuh Manager service is running
      systemd:
        name: wazuh-manager
        state: started
        enabled: yes

    # Optional: Gửi thông báo nếu cập nhật thành công
    - name: Send notification
      debug:
        msg: "Wazuh Manager has been successfully updated and restarted!"
