---
- name: Update Wazuh Manager
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install or update Wazuh Manager
      apt:
        name: wazuh-manager
        state: latest

    - name: Restart Wazuh Manager service
      service:
        name: wazuh-manager
        state: restarted

    - name: Check Wazuh Manager version
      command: /var/ossec/bin/wazuh-control info
      register: wazuh_version

    - name: Display Wazuh version
      debug:
        msg: "Wazuh Manager version: {{ wazuh_version.stdout }}"
