---
- hosts: all
  vars:
    wazuh_manager_version: 3.12.2-1
    wazuh_agent_version: 3.12.2-1
    elastic_stack_version: 7.6.2
    node_options: --max-old-space-size=2048
    wazuh_app_url: https://packages.wazuh.com/wazuhapp/wazuhapp
  tasks:
    - name: Wazuh manager and filebeat update
      block:
        #Stopping manager and API 
        - name: ensure wazuh-manager is stopped
          service:
            name: wazuh-manager
            state: stopped
        - name: ensure wazuh-api is stopped
          service:
            name: wazuh-api
            state: stopped
        #Upgrading Wazuh manager and API
        - name: Debian/Ubuntu | Install wazuh-manager
          apt:
            name:
              - "wazuh-manager={{ wazuh_manager_version }}"
            state: present
            cache_valid_time: 3600
            install_recommends: false
          register: wazuh_manager_main_packages_installed
          until: wazuh_manager_main_packages_installed is succeeded
          when:
            - ansible_os_family|lower == "debian"

        - name: Debian/Ubuntu | Install wazuh-api
          apt:
            name:
              - "wazuh-api={{ wazuh_manager_version }}"
            state: present
            cache_valid_time: 3600
            install_recommends: false
          register: wazuh_manager_main_packages_installed
          until: wazuh_manager_main_packages_installed is succeeded
          when:
            - ansible_os_family|lower == "debian"

        - name: CentOS/RedHat/Amazon | Install wazuh-manager
          package:
            name: "wazuh-manager-{{ wazuh_manager_version }}"
            state: present
          register: wazuh_manager_main_packages_installed
          until: wazuh_manager_main_packages_installed is succeeded
          when:
            - ansible_os_family|lower == "redhat"
        - name: CentOS/RedHat/Amazon | Install wazuh-api
          package:
            name: "wazuh-api-{{ wazuh_manager_version }}"
            state: present
          register: wazuh_api_main_packages_installed
          until: wazuh_api_main_packages_installed is succeeded
          when:
            - ansible_os_family|lower == "redhat"
        #Restarting Wazuh manager and API
        - name: restart manager
          service:
            name: wazuh-manager
            state: restarted
        - name: restart api
          service:
            name: wazuh-api
            state: restarted

        # Filebeat
        - name: ensure filebeat is stopped
          service:
            name: filebeat
            state: stopped

        - name: CentOS/RedHat |  Install Filebeat.
          package: name=filebeat-{{ elastic_stack_version }} state=present
          register: filebeat_installing_package
          until: filebeat_installing_package is succeeded
          when:
            - ansible_os_family|lower == "redhat"
        - name: Debian/Ubuntu | Install Filebeat.
          apt:
            name: filebeat={{ elastic_stack_version }}
            state: present
            cache_valid_time: 3600
          register: filebeat_installing_package_debian
          until: filebeat_installing_package_debian is succeeded
          when:
            - ansible_os_family|lower == "debian"

        - name: restart filebeat
          service:
            name: filebeat
            state: restarted
      when:
        - inventory_hostname in groups['manager']

    - name: Wazuh agent update
      block:
        #Stopping agent 
        - name: ensure wazuh-agent is stopped
          service:
            name: wazuh-agent
            state: stopped

        - name: Linux Debian | Install wazuh-agent
          apt:
            name: "wazuh-agent={{ wazuh_agent_version }}-1"
            state: present
            cache_valid_time: 3600
          when:
            - ansible_os_family|lower == "debian"

        - name: Linux CentOS/RedHat | Install wazuh-agent
          package:
            name: wazuh-agent-{{ wazuh_agent_version }}
            state: present
          async: 90
          poll: 30
          when:
            - ansible_os_family|lower == "redhat"

        - name: restart agent
          service:
            name: wazuh-agent
            state: restarted
      when:
        - inventory_hostname in groups['agent']

    - name: Elasticsearch update
      block:
        - name: ensure elasticsearch is stopped
          service:
            name: elasticsearch
            state: stopped

        - name: Debian/Ubuntu | Install Elasticsarch
          apt:
            name: "elasticsearch={{ elastic_stack_version }}"
            state: present
            cache_valid_time: 3600
          register: elasticsearch_main_packages_installed
          until: elasticsearch_main_packages_installed is succeeded
          when:
            - ansible_os_family|lower == "debian"
        - name: RedHat/CentOS/Fedora | Install Elasticsarch
          package: name=elasticsearch-{{ elastic_stack_version }} state=present
          when:
            - ansible_os_family|lower == "redhat"
        - name: restart elasticsearch
          service:
            name: elasticsearch
            state: restarted
      when:
        - inventory_hostname in groups['elasticsearch']

    - name: Kibana update
      block:
        - name: ensure kibana is stopped
          service:
            name: kibana
            state: stopped

        - name: Debian/Ubuntu | Install Kibana
          apt:
            name: "kibana={{ elastic_stack_version }}"
            state: present
            cache_valid_time: 3600
          register: installing_kibana_package
          until: installing_kibana_package is succeeded
          when:
            - ansible_os_family|lower == "debian"
      
        - name: RedHat/CentOS/Fedora | Install Kibana
          package: name=kibana-{{ elastic_stack_version }} state=present
          register: installing_kibana_package
          until: installing_kibana_package is succeeded
          when:
            - ansible_os_family|lower == "redhat"

        - name: Install Wazuh Plugin (can take a while)
          shell: >-
            NODE_OPTIONS="{{ node_options }}" /usr/share/kibana/bin/kibana-plugin install
            {{ wazuh_app_url }}-{{ wazuh_manager_version }}_{{ elastic_stack_version }}.zip
          args:
            executable: /bin/bash
            creates: /usr/share/kibana/plugins/wazuh/package.json
            chdir: /usr/share/kibana
          become: yes
          become_user: kibana
          notify: restart kibana

        - name: Kibana optimization (can take a while)
          shell: NODE_OPTIONS="{{ node_options }}" /usr/share/kibana/bin/kibana --optimize
          args:
            executable: /bin/bash
          become: yes
          become_user: kibana
          changed_when: false

        - name: restart kibana
          service:
            name: kibana
            state: restarted
      when:
        - inventory_hostname in groups['kibana']
