---
- name: Update and Backup Wazuh
  hosts: 192.168.10.187
  become: true
  gather_facts: no

  tasks:
    - name: Ensure Wazuh Manager is updated to the latest version
      apt:
        name: wazuh-manager
        state: latest
        update_cache: yes
      register: update_result

    - name: Notify if Wazuh Manager was updated
      debug:
        msg: "Wazuh Manager has been updated to the latest version."
      when: update_result.changed

    - name: Create backup directory if it doesn't exist
      file:
        path: /var/ossec/backup
        state: directory
        mode: '0755'
        owner: wazuh
        group: wazuh

    - name: Create backup of Wazuh configuration and data
      command: tar -czf /var/ossec/backup/wazuh_backup_{{ ansible_date_time.date }}.tar.gz /var/ossec/
      args:
        creates: /var/ossec/backup/wazuh_backup_{{ ansible_date_time.date }}.tar.gz
      register: backup_result
      failed_when: backup_result.rc != 0

    - name: Notify if backup was successful
      debug:
        msg: "Backup created successfully at /var/ossec/backup/wazuh_backup_{{ ansible_date_time.date }}.tar.gz"
      when: backup_result.rc == 0

    - name: Copy the backup to a secure location
      copy:
        src: /var/ossec/backup/wazuh_backup_{{ ansible_date_time.date }}.tar.gz
        dest: /home/wazuh/backup/wazuh_backup_{{ ansible_date_time.date }}.tar.gz
        owner: wazuh
        group: wazuh
        remote_src: yes
      register: copy_result

    - name: Notify if backup was copied successfully
      debug:
        msg: "Backup copied successfully to /home/wazuh/backup/wazuh_backup_{{ ansible_date_time.date }}.tar.gz"
      when: copy_result.changed

    - name: Clean up old backups older than 7 days
      find:
        paths: /var/ossec/backup
        age: 7d
        patterns: "*.tar.gz"
      register: old_backups

    - name: Remove old backups
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_backups.files }}"
      when: old_backups.matched > 0
